/* Cinematic Engine — Generated by Arbel */
(function(){
"use strict";

/* Preloader */
var preloader = document.getElementById("preloader");
var fill = preloader ? preloader.querySelector(".cne-preloader-fill") : null;
var loadPct = 0;
var loadTimer = setInterval(function(){
  loadPct += Math.random() * 20 + 5;
  if(loadPct > 100) loadPct = 100;
  if(fill) fill.style.width = loadPct + "%";
  if(loadPct >= 100){ clearInterval(loadTimer); setTimeout(function(){ if(preloader) preloader.classList.add("hidden"); initCinema(); },400); }
}, 150);

/* Lenis smooth scroll */
var lenis;
function initLenis(){
  if(window.innerWidth < 768) return;
  lenis = new Lenis({ duration: 1.2, easing: function(t){ return Math.min(1, 1.001 - Math.pow(2, -10 * t)); } });
  lenis.on("scroll", ScrollTrigger.update);
  gsap.ticker.add(function(time){ lenis.raf(time * 1000); });
  gsap.ticker.lagSmoothing(0);
}

/* Split text into chars */
function splitText(el){
  var text = el.textContent;
  var words = text.split(/\s+/);
  el.innerHTML = "";
  words.forEach(function(word, wi){
    var wSpan = document.createElement("span");
    wSpan.className = "cne-word";
    word.split("").forEach(function(ch){
      var cSpan = document.createElement("span");
      cSpan.className = "cne-char";
      cSpan.textContent = ch;
      wSpan.appendChild(cSpan);
    });
    el.appendChild(wSpan);
  });
  return el.querySelectorAll(".cne-char");
}

/* Scroll progress bar */
function initScrollProgress(){
  var bar = document.getElementById("scrollProgress");
  if(!bar) return;
  window.addEventListener("scroll", function(){
    var pct = window.scrollY / (document.documentElement.scrollHeight - window.innerHeight) * 100;
    bar.style.width = Math.min(pct, 100) + "%";
  });
}

/* Cubic-bezier to GSAP ease */
function parseBezierEase(str){
  if(!str || str.indexOf("cubic-bezier") !== 0) return str;
  var m = str.match(/cubic-bezier\(([^)]+)\)/);
  if(!m) return "none";
  var p = m[1].split(",").map(Number);
  return function(t){
    var cx=3*p[0],bx=3*(p[2]-p[0])-cx,ax=1-cx-bx;
    var cy=3*p[1],by=3*(p[3]-p[1])-cy,ay=1-cy-by;
    var lo=0,hi=1,mid;
    for(var i=0;i<16;i++){mid=(lo+hi)/2;var x=((ax*mid+bx)*mid+cx)*mid;if(x<t)lo=mid;else hi=mid;}
    return((ay*mid+by)*mid+cy)*mid;
  };
}

/* Init cinema engine */
function initCinema(){
  gsap.registerPlugin(ScrollTrigger);
  initLenis();
  initScrollProgress();

  var scenes = document.querySelectorAll(".cne-scene");
  scenes.forEach(function(scene){
    var shouldPin = scene.dataset.pin === "true";
    var duration = parseInt(scene.dataset.duration) || 100;

    if(shouldPin){
      ScrollTrigger.create({
        trigger: scene,
        start: "top top",
        end: "+=" + (duration) + "%",
        pin: true,
        pinSpacing: true,
        anticipatePin: 1
      });
    }

    var elems = scene.querySelectorAll("[data-scroll]");
    elems.forEach(function(el){
      var sd;
      try { sd = JSON.parse(el.dataset.scroll); } catch(e){ return; }
      if(!sd) return;

      /* Split text if flagged */
      var isSplit = el.dataset.splitText === "true";
      var chars;
      if(isSplit){ chars = splitText(el); }

      var tl = gsap.timeline({
        scrollTrigger: {
          trigger: scene,
          start: "top top",
          end: "+=" + duration + "%",
          scrub: 1
        }
      });

      var startPct = sd.start || 0;
      var endPct = sd.end || 1;
      var easeVal = parseBezierEase(sd.ease || "none");

      /* Build from/to tweens for each property */
      var props = ["opacity","x","y","scale","rotation"];
      props.forEach(function(prop){
        if(!sd[prop]) return;
        var vals = Array.isArray(sd[prop]) ? sd[prop] : [sd[prop]];
        if(vals.length < 2) return;

        var target = isSplit ? chars : el;
        var segLen = (endPct - startPct) / (vals.length - 1);

        for(var i = 0; i < vals.length - 1; i++){
          var from = {}; from[prop] = vals[i];
          var to = {}; to[prop] = vals[i+1];
          to.ease = easeVal;
          if(isSplit) to.stagger = 0.02;
          var pos = startPct + (segLen * i);
          tl.fromTo(target, from, to, pos);
        }
      });

      /* Special properties (blur, clip-path, 3D) */
      var specialProps = ["blur","clipPath","rotateX","rotateY","skewX","skewY"];
      specialProps.forEach(function(prop){
        if(!sd[prop]) return;
        var vals = Array.isArray(sd[prop]) ? sd[prop] : [sd[prop]];
        if(vals.length < 2) return;

        var target = isSplit ? chars : el;
        var segLen = (endPct - startPct) / (vals.length - 1);

        for(var i = 0; i < vals.length - 1; i++){
          var from = {}, to = {};
          if(prop === "blur"){
            from.filter = "blur(" + vals[i] + "px)";
            to.filter = "blur(" + vals[i+1] + "px)";
          } else if(prop === "clipPath"){
            from.clipPath = vals[i];
            to.clipPath = vals[i+1];
          } else {
            from[prop] = vals[i];
            to[prop] = vals[i+1];
          }
          to.ease = easeVal;
          if(isSplit) to.stagger = 0.02;
          var pos = startPct + (segLen * i);
          tl.fromTo(target, from, to, pos);
        }
      });
    });

    /* Parallax */
    var pxEls = scene.querySelectorAll("[data-parallax]");
    pxEls.forEach(function(pxEl){
      var depth = parseFloat(pxEl.dataset.parallax) || 1;
      gsap.to(pxEl, {
        y: (depth - 1) * -200,
        ease: "none",
        scrollTrigger: { trigger: scene, start: "top bottom", end: "bottom top", scrub: true }
      });
    });
  });

  /* 3D Background Effects */
  document.querySelectorAll(".cne-bg3d").forEach(function(container){
    var type = container.dataset.bg3d;
    var c1 = container.dataset.color1 || "#6c5ce7";
    var c2 = container.dataset.color2 || "#00cec9";
    var intensity = parseInt(container.dataset.intensity) || 5;
    var speed = container.dataset.speed || "medium";
    var speedMs = speed === "slow" ? 20 : speed === "fast" ? 6 : 12;

    if(type === "gradient-orbs"){
      for(var i = 0; i < Math.min(intensity, 8); i++){
        var orb = document.createElement("div");
        orb.className = "cne-bg3d-orb";
        var size = 200 + Math.random() * 300;
        orb.style.width = size + "px"; orb.style.height = size + "px";
        orb.style.background = i % 2 === 0 ? c1 : c2;
        orb.style.top = Math.random() * 80 + "%";
        orb.style.left = Math.random() * 80 + "%";
        orb.style.setProperty("--orb-speed", (speedMs + Math.random() * 8) + "s");
        orb.style.animationDelay = -(Math.random() * speedMs) + "s";
        container.appendChild(orb);
      }
    }

    if(type === "particle-field"){
      var count = intensity * 8;
      for(var j = 0; j < Math.min(count, 60); j++){
        var p = document.createElement("div");
        p.className = "cne-bg3d-particle";
        var pSize = 2 + Math.random() * 4;
        p.style.width = pSize + "px"; p.style.height = pSize + "px";
        p.style.background = Math.random() > 0.5 ? c1 : c2;
        p.style.left = Math.random() * 100 + "%";
        p.style.opacity = 0.3 + Math.random() * 0.5;
        p.style.setProperty("--p-speed", (speedMs + Math.random() * 15) + "s");
        p.style.animationDelay = -(Math.random() * 30) + "s";
        container.appendChild(p);
      }
    }

    if(type === "aurora"){
      for(var a = 0; a < Math.min(intensity, 5); a++){
        var au = document.createElement("div");
        au.className = "cne-bg3d-aurora";
        au.style.setProperty("--aurora-c1", c1);
        au.style.setProperty("--aurora-c2", c2);
        au.style.setProperty("--aurora-speed", (speedMs + a * 3) + "s");
        au.style.animationDelay = -(a * 2) + "s";
        au.style.opacity = 0.2 + (a * 0.1);
        container.appendChild(au);
      }
    }

    if(type === "mesh-gradient"){
      var mesh = document.createElement("div");
      mesh.className = "cne-bg3d-mesh";
      var stops = "radial-gradient(circle at 20% 30%, " + c1 + " 0%, transparent 50%),radial-gradient(circle at 80% 70%, " + c2 + " 0%, transparent 50%),radial-gradient(circle at 50% 50%, " + c1 + " 0%, transparent 70%)";
      mesh.style.background = stops;
      mesh.style.opacity = Math.min(intensity * 0.08, 0.6);
      mesh.style.setProperty("--mesh-speed", speedMs * 3 + "s");
      container.appendChild(mesh);
    }

    if(type === "noise-fog"){
      for(var f = 0; f < Math.min(intensity, 6); f++){
        var fog = document.createElement("div");
        fog.className = "cne-bg3d-orb";
        var fSize = 300 + Math.random() * 500;
        fog.style.width = fSize + "px"; fog.style.height = fSize + "px";
        fog.style.background = f % 2 === 0 ? c1 : c2;
        fog.style.filter = "blur(" + (100 + Math.random() * 80) + "px)";
        fog.style.opacity = 0.15 + Math.random() * 0.15;
        fog.style.top = Math.random() * 100 + "%";
        fog.style.left = Math.random() * 100 + "%";
        fog.style.setProperty("--orb-speed", (speedMs * 2 + Math.random() * 10) + "s");
        fog.style.animationDelay = -(Math.random() * 20) + "s";
        container.appendChild(fog);
      }
    }

    if(type === "starfield"){
      var starCount = intensity * 15;
      for(var s = 0; s < Math.min(starCount, 100); s++){
        var star = document.createElement("div");
        star.className = "cne-bg3d-star";
        var sSize = 1 + Math.random() * 3;
        star.style.width = sSize + "px"; star.style.height = sSize + "px";
        star.style.top = Math.random() * 100 + "%";
        star.style.left = Math.random() * 100 + "%";
        star.style.setProperty("--star-speed", (speedMs * 0.3 + Math.random() * 3) + "s");
        star.style.animationDelay = -(Math.random() * 5) + "s";
        container.appendChild(star);
      }
    }

    if(type === "wave-grid"){
      var cols = 20; var rows = 12;
      for(var gy = 0; gy < rows; gy++){
        var line = document.createElement("div");
        line.className = "cne-bg3d-grid-line";
        line.style.width = "100%"; line.style.height = "1px";
        line.style.top = (gy / rows * 100) + "%";
        line.style.left = "0";
        line.style.color = c1;
        container.appendChild(line);
      }
      for(var gx = 0; gx < cols; gx++){
        var vline = document.createElement("div");
        vline.className = "cne-bg3d-grid-line";
        vline.style.width = "1px"; vline.style.height = "100%";
        vline.style.top = "0";
        vline.style.left = (gx / cols * 100) + "%";
        vline.style.color = c2;
        container.appendChild(vline);
      }
      gsap.to(container.querySelectorAll(".cne-bg3d-grid-line"), {
        opacity: 0.3,
        duration: speedMs * 0.5,
        stagger: { each: 0.05, repeat: -1, yoyo: true },
        ease: "sine.inOut"
      });
    }
  });

  /* Nav auto-hide on scroll */
  var nav = document.querySelector(".cne-nav");
  if(nav){
    var lastY = 0;
    window.addEventListener("scroll", function(){
      var y = window.scrollY;
      if(y > lastY && y > 100) nav.classList.add("hidden");
      else nav.classList.remove("hidden");
      lastY = y;
    });
  }
}
})();
