/* Main interactions — Generated by Arbel */
(function(){
"use strict";

/* Custom cursor */
var cursor = document.createElement("div");
cursor.className = "cne-cursor";
document.body.appendChild(cursor);
var cx = 0, cy = 0, tx = 0, ty = 0;
document.addEventListener("mousemove", function(e){ tx = e.clientX; ty = e.clientY; });
(function tick(){ cx += (tx - cx) * 0.15; cy += (ty - cy) * 0.15; cursor.style.transform = "translate(" + cx + "px," + cy + "px)"; requestAnimationFrame(tick); })();

var cursorCSS = document.createElement("style");
cursorCSS.textContent = ".cne-cursor{position:fixed;top:-10px;left:-10px;width:20px;height:20px;border:1.5px solid rgba(255,255,255,0.5);border-radius:50%;pointer-events:none;z-index:9998;mix-blend-mode:difference;transition:width 0.3s,height 0.3s,border-color 0.3s;will-change:transform} a:hover~.cne-cursor,.cne-cursor.hover{width:44px;height:44px;border-color:#6c5ce7}";
document.head.appendChild(cursorCSS);

document.querySelectorAll("a, button").forEach(function(el){
  el.addEventListener("mouseenter", function(){ cursor.classList.add("hover"); });
  el.addEventListener("mouseleave", function(){ cursor.classList.remove("hover"); });
});
})();
